version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - 7077:80
        logging:
            driver: none
    db:
        container_name: redlock
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: Redlock
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - "9906:3306"
        volumes:
        - ./mysql-dump:/docker-entrypoint-initdb.d/
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8000:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
